//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.Carts = new HashSet<Cart>();
        }
        [Required(ErrorMessage = "A Coupon Code is required")]
        [StringLength(20, MinimumLength = 10, ErrorMessage = "Invalid Coupon Code. Minumum Length = 10, Max = 20")]
        public string Code { get; set; }
        public string CustomerName { get; set; }
        [Range(5, 90, ErrorMessage = "Discount Percentage must be between 5 and 90 Percent")]
        public Nullable<int> Discount { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
