//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Faq
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Category must be less than 50 Characters")]
        [StringLength(50)]
        public string Category { get; set; }
        [Required(ErrorMessage = "Question must be less than 150 Characters")]
        [StringLength(150)]
        public string Question { get; set; }
        public string Answer { get; set; }
    }
}
