//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        [Required(ErrorMessage = "Type of Payment Method is required")]
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Tax { get; set; }
        [Required(ErrorMessage = "Total Cost of Payment is required")]
        public Nullable<int> Total { get; set; }
        [DisplayName("Payment Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
