//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping()
        {
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "A Shipping Carrier is required")]
        [StringLength(20, MinimumLength = 2)]
        public string ShippingCarrier { get; set; }
        [Range(0, 1000, ErrorMessage = "Shipping Cost cannot exceed 1000.")]
        public string ShippingCost { get; set; }
        [DisplayName("Expected Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        [DisplayName("Arrival Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string Status { get; set; }
        [Required(ErrorMessage = "A Location is required")]
        [StringLength(50, MinimumLength = 2)]
        public string Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
